version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest  # Use PostgreSQL with pgvector pre-installed
    container_name: conversy_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=conversy
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Corrected volume path
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
