import type { Metadata } from "next";
import { ClientAuthProvider } from "@/context/ClientAuthProvider";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Handlee&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.__CHAT_CONFIG__ = {
                apiKey: '${process.env.NEXT_PUBLIC_CHAT_API_KEY || ""}',
                theme: {
                  primary: '#2563eb',
                  secondary: '#ffffff',
                  text: '#1f2937',
                  bubble: '#2563eb'
                },
                position: 'bottom-right',
                title: 'Chat with us',
                placeholder: 'Type your message...'
              };
            `,
          }}
        />
        <script src="/widget/chatbot.js" async />
        <script src="/widget/chat-init.js" async />
      </head>
      <ClientAuthProvider>
        <body>
          <NextTopLoader color="#000" />
          {children}
        </body>
      </ClientAuthProvider>
    </html>
  );
}
