import type { Metadata } from "next";
import { ClientAuthProvider } from "@/context/ClientAuthProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientAuthProvider>
        <body>{children}</body>
      </ClientAuthProvider>
    </html>
  );
}
